### ISSUE TITLE
any chance you could upload the kicad files?

### ISSUE THREAD

**Issue by KeLaiFu** [ecruz480/eurorack-modules#1]
First of all , thanks for your contributions to the DIY scene, I'd like to play around with your layout of this, maybe make a smaller version etc. Is there any chance you could upload the kicad files (or just the .sch)?

Cheers!

**Comment by ecruz480** [comment]
Hi KeLaiFu -

Thank you for the kind words! I'd be happy to share with you the KiCAD schematic file(s). What module are you interested in?

I have special locations for KiCAD libraries, so there might be some missing aspects from the schematic without the necessary supporting files in the right locations, but you should have enough info along with the uploaded PDF of the schematic to start tinkering!

**Comment by KeLaiFu** [comment]
Hey, thanks!
I was interested in the MS20 filter, if you can add the files for that one, that would be awesome. 
The actual kicad pcb files would be useful too since I'll probably just edit the layout of the PCB, not the circuit itself (I'll probably break it), but anything will help...

**Comment by ecruz480** [comment]
Let me know if you are able to download and view. I am using KiCAD version 7.0.1


[ks20_KiCAD_Project_v0.zip](https://github.com/ecruz480/eurorack/files/13866908/ks20_KiCAD_Project_v0.zip)

**Comment by KeLaiFu** [comment]
looks great! everything loaded up without any complaints about footprints etc, I'll play around with the layout and get the PCBs ordered.
Thanks!

**Comment by KeLaiFu** [comment]
Well its been a few months and I have finally got my version of this finished, although not without some concerns it isnt quite working properly, hence me pestering you once again.

I built the module almost exactly as the original schematic, just in smd. The one thing i changed was switching the decoupling caps to ceramics instead of film in the original layout. 

When i first tried the module I had a 10k pot for the freq as per schem, but i found this had a very small sweet spot where it was functional, and the majority of the dial was either off or maxed. Switching for a 1m pot helps this a little, but it's still not as I would expect. 

I doubt the cap switch could have made this happen, do you have any ideas what I could have broken?

**Comment by ecruz480** [comment]
Hi KeLaiFu -

What type of potentiometer have you implemented (linear, log, exp)? This could effect how the frequency range sweeps across values. I chose linear as I am not super worried about working within specific audio ranges, but you might want to add some type of tapered resistor network to better match the response curve to your liking. Unfortunately, I don't have great insight into a fix for this particular module as it is a clone of Kausstronics. 

In the original [Rene Schmitz design](https://www.schmitzbits.de/ms20.html), he uses a 47k Linear taper potentiometer. So I would think your best bet it to experiment with different values as you have been doing.

Please feel free to upload any schematic, pictures, audio files, videos, etc and I can take a look at them as well.

Best of luck!

**Comment by ecruz480** [comment]
KeLaiFu -

I took a look at the schematic again and failed to notice the trimmer pot on the output just before the current mirror (it is listed as RV1 in my schematic). I messed around with it a bit and got it locked in at a value where I now have a much more even sweep across my frequency ranges. If you have not tried adjusting it yet, this could potentially help solve your issue.

Let me know what works!

**Comment by KeLaiFu** [comment]
Hi Ethan, thanks for your efforts to help, it's very much appreciated.

I've played with the module a little since and here's a more detailed description of what it does. To be honest, this may well be perfectly normal for an MS20 filter so I may just be finding issues where there arn't any.

I generally get the filter completely closed for 30% of the range (depending on if it's in HP or LP mode). from there, from between 11 and 12:30 o'clock in the pot, the resonance kicks in, however, this gets extended to around 1:30 with an A1M pot (using an X10k pot means the range is much smaller). 
The rest of the range of the pot is purely the input signal.

This, may be the normal performance but i feel that the range where the resonance can be swept should be larger, with less of the dial being fully closed or fully open.

I've also noticed that if the drive is too high, the audio can get a little stuttery, although I guess that could be 'over' drive...


While writing the above, I checked the schematics you linked and ended up looking at a few more similar schematics and I noticed on one, the design includes a 33k and a 56k on the + and -12 going to the potentiometer. I botched a couple of 47k resistors into the circuit and it does add a lot more range to the sweep. I don't know if I could potentially be breaking something, but at least in my initial trial, it seems much better.

Sorry for the scattered reply! I may have fixed my own problem is explaining it to you, so... result!

**Comment by ecruz480** [comment]
Hi KeLaiFu -

Glad to see progress being made. It sound like you are modifying the potentiometer resistance curve which is a valid way to change the range of your filter sweep. If you prefer one characteristic or another depending on the resistors you add to your design, it will be "fixed" in that way. Otherwise, you can try playing with the trimmer pot to adjust the range as well for a less permanent solution (whichever option works for you the best).

The overdrive is one of the iconic features of the MS-20 filter, so much of its character comes from playing with the resonance and drive settings. I am also not the most well versed in the MS-20 capabilities, so I am still learning much as I play with it and learn how to wield it :)

Again, best of luck and thanks for contributing!
